Disable testing

diff --git a/.github/workflows/ci-pytorch_test-full.yml b/.github/workflows/ci-pytorch_test-full.yml
--- a/.github/workflows/ci-pytorch_test-full.yml
+++ b/.github/workflows/ci-pytorch_test-full.yml
@@ -107,69 +107,69 @@ jobs:
       run: pip freeze >> $GITHUB_STEP_SUMMARY
       shell: bash
 
-    - name: Reinstall Horovod if necessary
-      if: runner.os != 'windows'
-      env:
-        HOROVOD_BUILD_ARCH_FLAGS: "-mfma"
-        HOROVOD_WITHOUT_MXNET: 1
-        HOROVOD_WITHOUT_TENSORFLOW: 1
-      run: |
-        HOROVOD_BUILT=$(python -c "import horovod.torch; horovod.torch.nccl_built(); print('SUCCESS')" || true)
-        if [[ $HOROVOD_BUILT != "SUCCESS" ]]; then
-          pip uninstall -y horovod
-          grep "horovod" requirements/pytorch/strategies.txt > requirements/pytorch/horovod.txt
-          pip install --no-cache-dir -r requirements/pytorch/horovod.txt
-        fi
-        horovodrun --check-build
-        python -c "import horovod.torch"
-      shell: bash
+    # - name: Reinstall Horovod if necessary
+    #   if: runner.os != 'windows'
+    #   env:
+    #     HOROVOD_BUILD_ARCH_FLAGS: "-mfma"
+    #     HOROVOD_WITHOUT_MXNET: 1
+    #     HOROVOD_WITHOUT_TENSORFLOW: 1
+    #   run: |
+    #     HOROVOD_BUILT=$(python -c "import horovod.torch; horovod.torch.nccl_built(); print('SUCCESS')" || true)
+    #     if [[ $HOROVOD_BUILT != "SUCCESS" ]]; then
+    #       pip uninstall -y horovod
+    #       grep "horovod" requirements/pytorch/strategies.txt > requirements/pytorch/horovod.txt
+    #       pip install --no-cache-dir -r requirements/pytorch/horovod.txt
+    #     fi
+    #     horovodrun --check-build
+    #     python -c "import horovod.torch"
+    #   shell: bash
 
-    - name: Cache datasets
-      uses: actions/cache@v2
-      with:
-        path: Datasets
-        key: pl-dataset
+    # - name: Cache datasets
+    #   uses: actions/cache@v2
+    #   with:
+    #     path: Datasets
+    #     key: pl-dataset
 
-    - name: Sanity check
-      run: python requirements/pytorch/check-avail-extras.py
+    # - name: Sanity check
+    #   run: python requirements/pytorch/check-avail-extras.py
 
-    - name: Testing PyTorch
-      working-directory: tests/tests_pytorch
-      # NOTE: do not include coverage report here, see: https://github.com/nedbat/coveragepy/issues/1003
-      run: coverage run --source pytorch_lightning -m pytest -v --durations=50 --junitxml=results-${{ runner.os }}-py${{ matrix.python-version }}-${{ matrix.requires }}-${{ matrix.release }}.xml
+    # - name: Testing PyTorch
+    #   working-directory: tests/tests_pytorch
+    #   # NOTE: do not include coverage report here, see: https://github.com/nedbat/coveragepy/issues/1003
+    #   run: coverage run --source pytorch_lightning -m pytest -v --durations=50 --junitxml=results-${{ runner.os }}-py${{ matrix.python-version }}-${{ matrix.requires }}-${{ matrix.release }}.xml
 
-    - name: Upload pytest results
-      uses: actions/upload-artifact@v2
-      with:
-        name: unittest-results-${{ runner.os }}-py${{ matrix.python-version }}-${{ matrix.requires }}-${{ matrix.release }}
-        path: tests/tests_pytorch/results-${{ runner.os }}-py${{ matrix.python-version }}-${{ matrix.requires }}-${{ matrix.release }}.xml
-      if: failure()
+    # - name: Upload pytest results
+    #   uses: actions/upload-artifact@v2
+    #   with:
+    #     name: unittest-results-${{ runner.os }}-py${{ matrix.python-version }}-${{ matrix.requires }}-${{ matrix.release }}
+    #     path: tests/tests_pytorch/results-${{ runner.os }}-py${{ matrix.python-version }}-${{ matrix.requires }}-${{ matrix.release }}.xml
+    #   if: failure()
 
-    - name: Prepare Examples
-      run: |
-        # adjust versions according installed Torch version
-        python ./requirements/pytorch/adjust-versions.py requirements/pytorch/examples.txt
-        pip install -r requirements/pytorch/examples.txt --find-links https://download.pytorch.org/whl/cpu/torch_stable.html --upgrade
+    # - name: Prepare Examples
+    #   run: |
+    #     # adjust versions according installed Torch version
+    #     python ./requirements/pytorch/adjust-versions.py requirements/pytorch/examples.txt
+    #     pip install -r requirements/pytorch/examples.txt --find-links https://download.pytorch.org/whl/cpu/torch_stable.html --upgrade
 
-    - name: Run Examples
-      working-directory: ./examples
-      run: python -m pytest test_pl_examples.py -v --durations=10
+    # - name: Run Examples
+    #   working-directory: ./examples
+    #   run: python -m pytest test_pl_examples.py -v --durations=10
 
-    - name: Statistics
-      if: success()
-      working-directory: tests/tests_pytorch
-      run: |
-        coverage report
-        coverage xml
+    # - name: Statistics
+    #   if: success()
+    #   working-directory: tests/tests_pytorch
+    #   run: |
+    #     coverage report
+    #     coverage xml
 
-    - name: Upload coverage to Codecov
-      uses: codecov/codecov-action@v1
-      if: always()
-      # see: https://github.com/actions/toolkit/issues/399
-      continue-on-error: true
-      with:
-        token: ${{ secrets.CODECOV_TOKEN }}
-        file: tests/tests_pytorch/coverage.xml
-        flags: cpu,pytest,python${{ matrix.python-version }}
-        name: CPU-coverage
-        fail_ci_if_error: false
+    # - name: Upload coverage to Codecov
+    #   uses: codecov/codecov-action@v1
+    #   if: always()
+    #   # see: https://github.com/actions/toolkit/issues/399
+    #   continue-on-error: true
+    #   with:
+    #     token: ${{ secrets.CODECOV_TOKEN }}
+    #     file: tests/tests_pytorch/coverage.xml
+    #     flags: cpu,pytest,python${{ matrix.python-version }}
+    #     name: CPU-coverage
+    #     fail_ci_if_error: false
